#!/usr/bin/env bash
# ===========================================================================
# Surgical Devices ERP — build & (re)deploy on EC2
#
#   ./deploy/deploy.sh           # build + start (generates .env on first run)
#   ./deploy/deploy.sh --seed    # also seed roles/permissions + an admin login
#                                  (run this ONCE, on the very first deploy)
#
# Override the public address (domain or Elastic IP) like:
#   APP_URL=https://erp.example.com ./deploy/deploy.sh
# ===========================================================================
set -euo pipefail

# Move to repo root regardless of where the script is invoked from.
cd "$(dirname "$0")/.."
ROOT="$(pwd)"
ENV_FILE="$ROOT/.env"

COMPOSE=(docker compose -f docker-compose.yml -f deploy/docker-compose.prod.yml)

SEED=false
[ "${1:-}" = "--seed" ] && SEED=true

# --- Detect public address ------------------------------------------------
detect_ip() {
  # EC2 IMDSv2 (token) then IMDSv1 fallback; finally localhost.
  local token ip
  token=$(curl -s -m 2 -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 60" 2>/dev/null || true)
  if [ -n "$token" ]; then
    ip=$(curl -s -m 2 -H "X-aws-ec2-metadata-token: $token" \
      http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)
  fi
  [ -z "${ip:-}" ] && ip=$(curl -s -m 2 http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)
  echo "${ip:-localhost}"
}

# --- Generate .env on first run -------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  echo "==> First run — generating $ENV_FILE"
  APP_KEY_GEN="base64:$(openssl rand -base64 32)"
  DB_PW_GEN="$(openssl rand -hex 16)"
  PUBLIC_ADDR="${APP_URL:-http://$(detect_ip)}"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh — edit MAIL_*/AWS_* for production email + S3 storage.
APP_KEY=$APP_KEY_GEN
APP_URL=$PUBLIC_ADDR
DB_PASSWORD=$DB_PW_GEN

# Email (defaults to writing to the log). For real email set, e.g.:
# MAIL_MAILER=smtp
# MAIL_HOST=email-smtp.eu-west-1.amazonaws.com
# MAIL_PORT=587
# MAIL_USERNAME=...
# MAIL_PASSWORD=...
# MAIL_FROM_ADDRESS=no-reply@yourdomain.com
MAIL_MAILER=log

# File storage. Default is the local disk (persisted in a docker volume).
# For S3: set FILESYSTEM_DISK=s3 and the AWS_* values below.
FILESYSTEM_DISK=local
# AWS_ACCESS_KEY_ID=
# AWS_SECRET_ACCESS_KEY=
# AWS_DEFAULT_REGION=eu-west-1
# AWS_BUCKET=
EOF
  echo "    APP_URL set to: $PUBLIC_ADDR"
  echo "    (edit $ENV_FILE if you use a domain / HTTPS, then re-run)"
fi

# --- Build & start ---------------------------------------------------------
echo "==> Building images and starting the stack"
"${COMPOSE[@]}" up -d --build

echo "==> Waiting for the API to finish migrating…"
sleep 8
"${COMPOSE[@]}" exec -T backend php artisan migrate --force || true
"${COMPOSE[@]}" exec -T backend php artisan storage:link || true

if [ "$SEED" = true ]; then
  echo "==> Seeding roles, permissions and demo accounts (first run only)"
  "${COMPOSE[@]}" exec -T backend php artisan db:seed --force
fi

ADDR=$(grep '^APP_URL=' "$ENV_FILE" | cut -d= -f2-)
echo ""
echo "✅ Deployed. Open: $ADDR"
echo "   Containers:"
"${COMPOSE[@]}" ps
echo ""
echo "   Logs:    docker compose -f docker-compose.yml -f deploy/docker-compose.prod.yml logs -f backend"
echo "   Stop:    docker compose -f docker-compose.yml -f deploy/docker-compose.prod.yml down"
if [ "$SEED" = true ]; then
  echo ""
  echo "   ⚠  Demo logins were seeded (password: password). Change/disable them"
  echo "      in the Users screen before real use."
fi
